# Set-up
sudo: false

language: c

# Cache builds
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# Goal: support latest 3 GHC major versions.
matrix:
  include:
  - env: RESOLVER="lts-6" # GHC 7.10
    addons: {apt: {packages: [libgmp-dev]}}
  - env: RESOLVER="lts-9" # GHC 8.0
    addons: {apt: {packages: [libgmp-dev]}}
  # - env: RESOLVER="lts-X" # GHC 8.2
  #   addons: {apt: {packages: [libgmp-dev]}}
  - env: RESOLVER="nightly"
    addons: {apt: {packages: [libgmp-dev]}}

# Download and unpack the stack executable
before_install:
- export PATH=/opt/ghc/$GHCVER/bin:$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# Run tests
script:
- ./test-build.sh
