# Set-up
sudo: false

language: c

# Cache builds
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# Goal: support latest 3 GHC major versions.
matrix:
  fast_finish: true
  include:
  - env: RESOLVER=lts-6 # GHC 7.10
    addons: {apt: {packages: [libgmp-dev]}}
  - env: RESOLVER=lts-9 # GHC 8.0
    addons: {apt: {packages: [libgmp-dev]}}
  # - env: RESOLVER= # GHC 8.2
  #   addons: {apt: {packages: [libgmp-dev]}}
  - env: RESOLVER=nightly
    addons: {apt: {packages: [libgmp-dev]}}
  allow_failures:
  - env: RESOLVER=nightly

# Download and unpack the stack executable
before_install:
- export PATH=/opt/ghc/$GHCVER/bin:$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# Run tests
script:
- stack --resolver=$RESOLVER setup
- stack --resolver=$RESOLVER build concurrency
- stack --resolver=$RESOLVER build dejafu
- stack --resolver=$RESOLVER build hunit-dejafu
- stack --resolver=$RESOLVER build tasty-dejafu
- stack --resolver=$RESOLVER build dejafu-tests
- stack --resolver=$RESOLVER exec dejafu-tests
