resolver: nightly-2016-06-20

packages:
- concurrency
- dejafu
- dejafu-tests
- hunit-dejafu
- tasty-dejafu

extra-deps:
- call-stack-0.1.0
- HUnit-1.6.0.0
- leancheck-0.6.2
- test-framework-hunit-0.3.0.2

nix:
  packages: [git]
