flags: {}

packages:
- concurrency
- dejafu
- dejafu-tests
- hunit-dejafu
- tasty-dejafu
# Until test-framework-hunit with HUnit 1.6 support is on Stackage:
# https://github.com/haskell/test-framework/pull/27
- location:
    git: https://github.com/haskell/test-framework.git
    commit: 7d9c1a67f41da960152657728da7813c533573f2
  subdirs:
  - hunit
  extra-dep: true

extra-deps:
- call-stack-0.1.0
- HUnit-1.6.0.0

resolver: nightly-2016-06-20

nix:
  packages: [git]
